databaseType = "MySql"
id = "aac107f7-7627-4b58-971d-f521e3891262"
name = "inventario_kardex"

[flyway]
callbackLocations = [ "filesystem:callbacks" ]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.mysql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.inventariokardex]
url = "jdbc:mysql://localhost:3306/inventario_kardex"
user = "root"
schemas = [ "inventario_kardex" ]
